---
title: "viz i"
output: github_document
---

```{r setup}
library(tidyverse)
library(patchwork)
```

```{r}
weather_df=read_csv("./weather_df.csv", na=c("NA","","."))

weather_df
```

##remember this plot?
```{r}
weather_df %>% 
  ggplot(aes(x= tmin, y =tmax, color=name)) +
  geom_point(alpha=0.5)
```

## labels
```{r}
weather_df %>% 
  ggplot(aes(x= tmin, y =tmax, color=name)) +
  geom_point(alpha=0.5)+
  labs(
    ttle="temperature plot",
    x="minimum daily temp",
    y="maximum daily temp",
    caption="data from rnoaa pakage; temparature in 2017."
  )
```

## scales 
start with the same plot

```{r}
weather_df %>% 
  ggplot(aes(x= tmin, y =tmax, color=name)) +
  geom_point(alpha=0.5)+
  labs(
    ttle="temperature plot",
    x="minimum daily temp",
    y="maximum daily temp",
    caption="data from rnoaa pakage; temparature in 2017."
  )+
  scale_x_continuous(
    breaks=c(-15,0,15),
    labels=c("-15 c", "0","15")
  ) +
  scale_y_continuous(
    trans="sqrt", #squreroot transformation
    position= "right"
  )

```


```{r}
weather_df %>% 
  ggplot(aes(x= tmin, y =tmax, color=name)) +
  geom_point(alpha=0.5)+
  labs(
    ttle="temperature plot",
    x="minimum daily temp",
    y="maximum daily temp",
    caption="data from rnoaa pakage; temparature in 2017."
  )+
  scale_x_continuous(
    breaks=c(-15,0,15),
    labels=c("-15 c", "0","15")
  ) +
  scale_y_continuous(
    trans="log" #log transformation
  )
```


```{r}
weather_df %>% 
  ggplot(aes(x= tmin, y =tmax, color=name)) +
  geom_point(alpha=0.5)+
  labs(
    ttle="temperature plot",
    x="minimum daily temp",
    y="maximum daily temp",
    caption="data from rnoaa pakage; temparature in 2017."
  ) +
  viridis::scale_color_viridis(
    name = "lacation",
    discrete = TRUE)
```

## themes
shift the legend
```{r}
weather_df %>% 
  ggplot(aes(x= tmin, y =tmax, color=name)) +
  geom_point(alpha=0.5)+
  labs(
    title="temperature plot",
    x="minimum daily temp",
    y="maximum daily temp",
    caption="data from rnoaa pakage; temparature in 2017."
  ) +
  viridis::scale_color_viridis(
    name = "lacation",
    discrete = TRUE) +
  theme(legend.position="bottom")
```

 change the overall theme
```{r}
weather_df %>% 
  ggplot(aes(x= tmin, y =tmax, color=name)) +
  geom_point(alpha=0.5)+
  labs(
    title="temperature plot",
    x="minimum daily temp",
    y="maximum daily temp",
    caption="data from rnoaa pakage; temparature in 2017."
  ) +
  viridis::scale_color_viridis(
    name = "lacation",
    discrete = TRUE) +
    theme_bw() ## theme balck and white 
```

```{r}
weather_df %>% 
  ggplot(aes(x= tmin, y =tmax, color=name)) +
  geom_point(alpha=0.5)+
  labs(
    title="temperature plot",
    x="minimum daily temp",
    y="maximum daily temp",
    caption="data from rnoaa pakage; temparature in 2017."
  ) +
  viridis::scale_color_viridis(
    name = "lacation",
    discrete = TRUE) +
    theme_minimal() ## theme balck and white 
```
```{r}
weather_df %>% 
  ggplot(aes(x= tmin, y =tmax, color=name)) +
  geom_point(alpha=0.5)+
  labs(
    title="temperature plot",
    x="minimum daily temp",
    y="maximum daily temp",
    caption="data from rnoaa pakage; temparature in 2017."
  ) +
  viridis::scale_color_viridis(
    name = "lacation",
    discrete = TRUE) +
    theme_classic() ## theme balck and white but without borders 
```
```{r}
weather_df %>% 
  ggplot(aes(x= tmin, y =tmax, color=name)) +
  geom_point(alpha=0.5)+
  labs(
    title="temperature plot",
    x="minimum daily temp",
    y="maximum daily temp",
    caption="data from rnoaa pakage; temparature in 2017."
  ) +
  viridis::scale_color_viridis(
    name = "lacation",
    discrete = TRUE) +
    ggthemes:: theme_economist() ## theme economist
```

```{r}
weather_df %>% 
  ggplot(aes(x= tmin, y =tmax, color=name)) +
  geom_point(alpha=0.5)+
  labs(
    title="temperature plot",
    x="minimum daily temp",
    y="maximum daily temp",
    caption="data from rnoaa pakage; temparature in 2017."
  ) +
  viridis::scale_color_viridis(
    name = "lacation",
    discrete = TRUE) +
    ggthemes::theme_excel() ## theme excel
```

## sequence matters for theme_minimal and bottom position
```{r}
weather_df %>% 
  ggplot(aes(x= tmin, y =tmax, color=name)) +
  geom_point(alpha=0.5)+
  labs(
    title="temperature plot",
    x="minimum daily temp",
    y="maximum daily temp",
    caption="data from rnoaa pakage; temparature in 2017."
  ) +
  viridis::scale_color_viridis(
    name = "lacation",
    discrete = TRUE) +
    theme_minimal() +
  theme(legend.position="bottom")
```

## setting options
```{r, eval = FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp= .6, #heigh/weigh
  out.width ="90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continous.color ="viridis",
  ggplot2.continous.fill ="viridis"
)

scale_color_discrete =scale_color_viridis_d
scale_fill_discrete =scale_fill_viridis_d
```




